CFC_Parachute = CFC_Parachute or {}

CFC_Parachute.DesignMaterials = false
CFC_Parachute.DesignMaterialNames = false
CFC_Parachute.DesignMaterialCount = false
CFC_Parachute.DesignWindow = false

CFC_Parachute.MenuToggleButtons = CFC_Parachute.MenuToggleButtons or {}
--[[ Contains tables with the following syntax to represent toggle buttons which will get added to the top of the design menu:
{
    HideState = BOOLEAN, -- Will hide the "Enabled/Disabled" text appended to the bottom of the tooltip
    TextOff = STRING, -- Text displayed when the button's value is 'off'
    TextOn = STRING, -- Text displayed when the button's value is 'on'
    ConVar = STRING, -- ConVar to be toggled (optional if OnClick and IsOn are defined)
    ConVarOff = STRING, -- Off value of ConVar (optional, default "0")
    ConVarOn = STRING, -- On value of ConVar (optional, default "1")
    ConVarServerChoice = STRING, -- Value which tells the client to use whatever value is used by the server in a convar of the same name with _sv appended (optional, does not exist by default)
    HoverText = STRING, -- Info text to display when the button is hovered over (optional, uses ConVar help text by default if ConVar is defined)
    OnClick = FUNCTION, -- Function to call when the button is pressed, overrides default functionality (optional)
    IsOn = FUNCTION, -- Returns true/false for if the button is on/off (optional if ConVar is defined)
    DButton = DBUTTON -- Autogenerated DButton object, used internally
}
--]]

local DESIGN_MATERIALS
local DESIGN_MATERIAL_NAMES
local DESIGN_MATERIAL_COUNT

local DESIGN_CHOICE = CreateConVar( "cfc_parachute_design", 1, { FCVAR_ARCHIVE, FCVAR_USERINFO, FCVAR_SERVER_CAN_EXECUTE, FCVAR_NEVER_AS_STRING }, "Your selected parachute design.", 1, 50000 )
local UNFURL_INVERT = CreateClientConVar( "cfc_parachute_unfurl_invert", 1, true, true, "Whether or not your parachute will be unfurled by default. Don't forget to open it!", 0, 1 )
CreateClientConVar( "cfc_parachute_unfurl_toggle", 0, true, true, "When enabled, pressing jump will toggle the unfurl state instead of holding it. Jumps won't toggle unfurl if chute is closed.", 0, 1 )


local MENU_COLOR = Color( 36, 41, 67, 255 )
local MENU_BAR_COLOR = Color( 42, 47, 74, 255 )

local BUTTON_TEXT_COLOR = Color( 255, 255, 255, 255 )
local BUTTON_TEXT_HOVERED_COLOR = Color( 255, 255, 255, 255 )
local BUTTON_OUTLINE_COLOR = Color( 255, 255, 255, 255 )
local BUTTON_PRESSED_COLOR = Color( 83, 227, 251, 255 )
local BUTTON_HOVERED_COLOR = Color( 31, 37, 61, 255 )
local BUTTON_OFF_COLOR = Color( 28, 33, 56, 255 )
local BUTTON_COLOR = Color( 42, 47, 74, 255 )

local TOOLTIP_COLOR = Color( 24, 29, 59, 255 )
local TOOLTIP_OUTLINE_COLOR = Color( 50, 58, 75, 255 )

local ANG_ZERO = Angle( 0, 0, 0 )
local ANG_GRAB_RIGHT_UPPERARM = Angle( 127.3, 331.3, 368.5 )
local ANG_GRAB_RIGHT_FOREARM = Angle( -6.8, 41.4, 57.5 )
local ANG_GRAB_RIGHT_HAND = Angle( 0, 26.7, 25.4 )
local ANG_GRAB_LEFT_UPPERARM = Angle( -72.1, -166, 127.3 )
local ANG_GRAB_LEFT_FOREARM = Angle( -11, 7.2, 26.5 )
local ANG_GRAB_LEFT_HAND = Angle( 0, 8.7, 0 )

local LFS_EXISTS

table.insert( CFC_Parachute.MenuToggleButtons, {
    HideState = true,
    TextOff = "Help/Info",
    TextOn = "Help/Info",
    HoverText = "Parachutes slow your descent and allow you to glide through the air faster than you can move on land." .. "\n\n" ..
        "Your chute will start off closed, and can be toggled open with left click." .. "\n" ..
        "While open, you can hold spacebar to furl the chute and fall a little faster." .. "\n" ..
        "Right clicking with the parachute SWEP will bring up this config menu." .. "\n" ..
        "You can select various chute designs and config options with the buttons below." .. "\n\n" ..
        "With your parachute open, you can switch to a different weapon and shoot from the air." .. "\n" ..
        "Be careful though, while your hands are occupied, you cannot close/furl/unfurl the chute and" .. "\n" ..
        "you will lose a lot of horizontal control." .. "\n" ..
        "Shooting too much will send you careening in a different direction, or even towards the ground."
} )

table.insert( CFC_Parachute.MenuToggleButtons, {
    TextOff = "Set unfurl to toggle mode",
    TextOn = "Set unfurl to hold mode",
    ConVar = "cfc_parachute_unfurl_toggle"
} )

table.insert( CFC_Parachute.MenuToggleButtons, {
    TextOff = "Start unfurled",
    TextOn = "Start furled",
    ConVar = "cfc_parachute_unfurl_invert",
    HoverText = UNFURL_INVERT:GetHelpText() .. "\n\n" ..
        "When a parachute is open, it will only slow your descent by a small amount." .. "\n" ..
        "To slow down all the way, your parachute must be open AND unfurled." .. "\n\n" ..
        "Leaving this setting ON will make it so chutes are unfurled by default," .. "\n" ..
        "causing spacebar to instead furl the chute up," .. "\n" ..
        "useful if you only ever want to fall at maximum slowness and not hold spacebar."
} )

local function trySetupLFS()
    if not LFS_EXISTS then return end

    CreateConVar( "cfc_parachute_lfs_eject_height", 500, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "The minimum height above the ground a player must be to auto-equip a parachute when ejecting from an LFS.", 0, 50000 )
    CreateConVar( "cfc_parachute_lfs_eject_launch_force", 1100, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "The upwards force applied to players when they launch out of an LFS plane.", 0, 50000 )
    CreateConVar( "cfc_parachute_lfs_eject_launch_bias", 25, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How many degrees the LFS eject launch should course-correct the player's trajectory to send them straight up, for if their plane is tilted.", 0, 90 )
    CreateConVar( "cfc_parachute_lfs_eject_stability_time", 5, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How many seconds a player is immune to parachute instability when they launch out of an LFS plane.", 0, 50000 )
    CreateConVar( "cfc_parachute_lfs_enter_radius", 800, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How close a player must be to enter an LFS if they are in a parachute and regular use detection fails. Makes it easier to get inside of an LFS for performing a Rendezook.", 0, 50000 )

    LFS_AUTO_CHUTE = CreateClientConVar( "cfc_parachute_lfs_auto_equip", 2, true, true, "Whether or not to auto-equip a parachute when ejecting from an LFS plane in the air.", 0, 2 )
    LFS_EJECT_LAUNCH = CreateClientConVar( "cfc_parachute_lfs_eject_launch", 2, true, true, "Whether or not to launch up high when ejecting from an LFS plane in the air. Useful for pulling off a Rendezook.", 0, 2 )

    LFS_AUTO_CHUTE_SV = CreateConVar( "cfc_parachute_lfs_auto_equip_sv", 1, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Whether or not to auto-equip a parachute when ejecting from an LFS plane in the air. Defines the default value for players.", 0, 1 )
    LFS_EJECT_LAUNCH_SV = CreateConVar( "cfc_parachute_lfs_eject_launch_sv", 1, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Whether or not to launch up high when ejecting from an LFS plane in the air. Useful for pulling off a Rendezook. Defines the default value for players.", 0, 1 )

    table.insert( CFC_Parachute.MenuToggleButtons, {
        TextOff = "Enable LFS Auto-Parachute",
        TextOn = "Disable LFS Auto-Parachute",
        ConVar = "cfc_parachute_lfs_auto_equip",
        ConVarServerChoice = "2"
    } )

    table.insert( CFC_Parachute.MenuToggleButtons, {
        TextOff = "Enable LFS Eject-Launch",
        TextOn = "Disable LFS Eject-Launch",
        ConVar = "cfc_parachute_lfs_eject_launch",
        ConVarServerChoice = "2"
    } )
end

function CFC_Parachute.CreateDesignPreview( x, y, ind, panel )
    local icon = vgui.Create( "ContentIcon", panel )
    icon:SetPos( x, y )
    icon:SetName( DESIGN_MATERIAL_NAMES[ind] )
    icon:SetMaterial( DESIGN_MATERIALS[ind] )

    icon.designInd = ind

    icon.DoClick = function()
        LocalPlayer():ConCommand( "cfc_parachute_design " .. ind )
    end

    local oldPaint = icon.Paint

    icon.Paint = function( _, w, h )
        render.SuppressEngineLighting( true )

        oldPaint( icon, w, h )

        render.SuppressEngineLighting( false )
    end

    return icon
end

function CFC_Parachute.PaintButton( panel ) -- Mimics appearance from CFC Loadouts for consistency
    panel:SetTextColor( BUTTON_TEXT_COLOR )

    panel.Paint = function( self, w, h )
        draw.RoundedBox( 0, 0, 0, w, h, BUTTON_OUTLINE_COLOR )

        if self:IsDown() then
            draw.RoundedBox( 0, 1, 1, w - 2, h - 2, BUTTON_PRESSED_COLOR )
        elseif self:IsHovered() then
            draw.RoundedBox( 0, 1, 1, w - 2, h - 2, BUTTON_HOVERED_COLOR )
        elseif panel.cfcParachuteIsOn and not panel.cfcParachuteIsOn() then
            draw.RoundedBox( 0, 1, 1, w - 2, h - 2, BUTTON_OFF_COLOR )
        else
            draw.RoundedBox( 0, 1, 1, w - 2, h - 2, BUTTON_COLOR )
        end
    end
end

function CFC_Parachute.PaintButtonHover( panel )
    panel:SetTextColor( BUTTON_TEXT_HOVERED_COLOR )

    panel.Paint = function( _, w, h )
        draw.RoundedBox( 0, 0, 0, w, h, TOOLTIP_OUTLINE_COLOR )
        draw.RoundedBox( 0, 1, 1, w - 2, h - 2, TOOLTIP_COLOR )
    end
end

function CFC_Parachute.CreateTooltip( panel, button )
    button:SetMouseInputEnabled( true )

    local tooltip = vgui.Create( "DLabel", panel )
    local tX, tY = panel:LocalCursorPos()
    local hoverText = button.cfcParachuteIntendedHoverText()
    local hoverState = button:IsHovered()
    local clamp = math.Clamp

    tooltip:SetText( hoverText )
    tooltip:SetPos( tX, tY )

    local pW, pH = panel:GetSize()
    local tW, tH = tooltip:GetTextSize()
    local textMargin = 10
    local panelMargin = 5
    local cursorOffsetX = -20
    local cursorOffsetY = 25

    tooltip:SetSize( tW + textMargin, tH + textMargin )
    tooltip:SetTextInset( textMargin / 2, 0 )
    CFC_Parachute.PaintButtonHover( tooltip )
    button.cfcParachuteTooltip = tooltip

    local xMax = pW - ( tW + textMargin + panelMargin )
    local yMax = pH - ( tH + textMargin + panelMargin )

    function button:Think()
        local isHovered = button:IsHovered()

        if isHovered then
            local x, y = panel:LocalCursorPos()

            x = clamp( x + cursorOffsetX, panelMargin, xMax )
            y = clamp( y + cursorOffsetY, panelMargin, yMax )

            tooltip:SetPos( x, y )
        end

        if hoverState ~= isHovered then
            hoverState = isHovered

            if hoverState then
                tooltip:MoveToFront()
                tooltip:Show()
            else
                tooltip:Hide()
            end
        end
    end
end

function CFC_Parachute.CreateToggleButton( x, y, ind, panel, w, h )
    local button = vgui.Create( "DButton", panel )
    local buttonData = CFC_Parachute.MenuToggleButtons[ind]

    local convarName = buttonData.ConVar
    local convar = convarName and GetConVar( convarName )
    local offVal = buttonData.ConVarOff or "0"
    local onVal = buttonData.ConVarOn or "1"
    local svVal = buttonData.ConVarServerChoice
    local offText = buttonData.TextOff or "Enable [UNDEFINED]"
    local onText = buttonData.TextOn or "Disable [UNDEFINED]"
    local hoverText = buttonData.HoverText or ( convar and convar:GetHelpText() )
    local hideState = buttonData.HideState

    button.cfcParachuteIsOn = buttonData.IsOn or function()
        if not convar then return true end

        local curVal = convar:GetString()

        return curVal == onVal or ( curVal == svVal and GetConVar( convarName .. "_sv" ):GetString() == onVal )
    end

    button.cfcParachuteIntendedText = function()
        return button.cfcParachuteIsOn() and onText or offText
    end

    button.cfcParachuteIntendedHoverText = function()
        if hideState then return hoverText end

        local text = hoverText .. "\n\n" .. "Currently "

        return text .. ( button.cfcParachuteIsOn() and "enabled" or "disabled" )
    end

    button:SetText( button.cfcParachuteIntendedText() )
    button:SetPos( x, y )
    button:SetSize( w or 200, h or 20 )
    CFC_Parachute.PaintButton( button )

    button.DoClick = buttonData.OnClick or function()
        local newVal = button.cfcParachuteIsOn() and offVal or onVal

        if not convarName then return end

        LocalPlayer():ConCommand( convarName .. " " .. newVal )
    end

    if hoverText then
        CFC_Parachute.CreateTooltip( panel, button )
    end

    buttonData.DButton = button

    return button
end

function CFC_Parachute.OpenDesignMenu()
    local window = CFC_Parachute.DesignWindow

    if window then
        window:Show()
        window:MakePopup()

        for _, data in ipairs( CFC_Parachute.MenuToggleButtons ) do
            local convarName = data.ConVar
            local serverChoice = data.ConVarServerChoice

            if convarName and serverChoice and GetConVar( convarName ):GetString() == serverChoice then
                local button = data.DButton

                if not button then continue end

                button:SetText( button.cfcParachuteIntendedText() )

                local tooltip = button.cfcParachuteTooltip

                if not tooltip then continue end

                tooltip:SetText( button.cfcParachuteIntendedHoverText() )
            end
        end

        return
    end

    local windowWidth = 800
    local windowHeight = 600

    window = vgui.Create( "DFrame" )
    window:SetSize( windowWidth, windowHeight )
    window:Center()
    window:SetTitle( "CFC Parachute Config" )
    window:SetDeleteOnClose( false )
    window:MakePopup()
    window:SetDeleteOnClose()

    CFC_Parachute.DesignWindow = window

    scrollPanel = vgui.Create( "DScrollPanel", window )
    scrollPanel:SetPos( 0, 20 )
    scrollPanel:SetSize( windowWidth, windowHeight )

    window.Paint = function( _, w, h )
        draw.RoundedBox( 8, 0, 0, w, h, MENU_COLOR )
        draw.RoundedBox( 8, 0, 0, w, 25, MENU_BAR_COLOR )
    end

    -- Toggle button setup
    local x = 0
    local y = 0
    local offsetX = 5
    local offsetY = 10
    local buttonWidth = 190
    local buttonHeight = 20
    local buttonGapX = 5
    local buttonGapY = 5

    for i = 1, #CFC_Parachute.MenuToggleButtons do
        if ( x + 1 ) * ( buttonWidth + buttonGapX ) > windowWidth then
            x = 0
            y = y + 1
        end

        CFC_Parachute.CreateToggleButton(
            x * ( buttonWidth + buttonGapX ) + offsetX,
            y * ( buttonHeight + buttonGapY ) + offsetY,
            i, scrollPanel, buttonWidth, buttonHeight
        )

        x = x + 1
    end

    -- Design button setup
    offsetX = 0

    if x > 0 then
        y = y + 1

        offsetY = offsetY + y * ( buttonHeight + buttonGapY )
    end

    x = 0
    y = 0
    buttonWidth = 120
    buttonHeight = 120

    for i = 1, CFC_Parachute.DesignMaterialCount do
        if ( x + 1 ) * buttonWidth >= windowWidth then
            x = 0
            y = y + 1
        end

        CFC_Parachute.CreateDesignPreview(
            x * ( buttonWidth + buttonGapX ) + offsetX,
            y * ( buttonHeight + buttonGapY ) + offsetY,
            i, scrollPanel
        )

        x = x + 1
    end
end

cvars.AddChangeCallback( "cfc_parachute_design", function( _, old, new )
    net.Start( "CFC_Parachute_SelectDesign" )
    net.WriteInt( math.floor( old ), 17 )
    net.WriteInt( math.floor( new ), 17 )
    net.SendToServer()
end )

hook.Add( "InitPostEntity", "CFC_Parachute_CheckOptionalDependencies", function()
    LFS_EXISTS = simfphys and simfphys.LFS and true

    trySetupLFS()

    for _, data in ipairs( CFC_Parachute.MenuToggleButtons ) do
        local convarName = data.ConVar

        if convarName then
            cvars.AddChangeCallback( convarName, function()
                local button = data.DButton

                if not button then return end

                button:SetText( button.cfcParachuteIntendedText() )

                local tooltip = button.cfcParachuteTooltip

                if not tooltip then return end

                tooltip:SetText( button.cfcParachuteIntendedHoverText() )
            end )
        end
    end
end )

net.Receive( "CFC_Parachute_DefineChuteDir", function()
    local chute = net.ReadEntity()
    local chuteDir = net.ReadVector()

    if not chute.SetChuteDirection then return end -- Somehow the function sometimes becomes nil while the parachute is still valid

    chute:SetChuteDirection( chuteDir )
end )

net.Receive( "CFC_Parachute_DefineChuteUnfurlStatus", function()
    local chute = net.ReadEntity()
    local unfurlState = net.ReadBool()

    if not chute.SetUnfurlStatus then return end -- Somehow the function sometimes becomes nil while the parachute is still valid

    chute:SetUnfurlStatus( unfurlState )
end )

net.Receive( "CFC_Parachute_DefineDesigns", function()
    DESIGN_MATERIALS = net.ReadTable()
    DESIGN_MATERIAL_NAMES = net.ReadTable()
    DESIGN_MATERIAL_COUNT = net.ReadInt( 17 )

    CFC_Parachute.DesignMaterials = DESIGN_MATERIALS
    CFC_Parachute.DesignMaterialNames = DESIGN_MATERIAL_NAMES
    CFC_Parachute.DesignMaterialCount = DESIGN_MATERIAL_COUNT
end )

net.Receive( "CFC_Parachute_SelectDesign", function()
    net.Start( "CFC_Parachute_SelectDesign" )
    net.WriteInt( 1, 17 )
    net.WriteInt( DESIGN_CHOICE:GetInt(), 17 )
    net.SendToServer()
end )

net.Receive( "CFC_Parachute_GrabChuteStraps", function()
    local ply = net.ReadEntity()
    local state = net.ReadBool()

    if not IsValid( ply ) then return end

    ply:SetIK( not state )

    if state then
        ply:AnimRestartGesture( GESTURE_SLOT_CUSTOM, ACT_GMOD_NOCLIP_LAYER, false )
        ply:AnimRestartGesture( GESTURE_SLOT_JUMP, ACT_HL2MP_IDLE_PASSIVE, false )
    else
        ply:AnimResetGestureSlot( GESTURE_SLOT_CUSTOM )
        ply:AnimResetGestureSlot( GESTURE_SLOT_JUMP )
    end

    local rightUpperarm = ply:LookupBone( "ValveBiped.Bip01_R_Upperarm" )
    local rightForearm = ply:LookupBone( "ValveBiped.Bip01_R_Forearm" )
    local rightHand = ply:LookupBone( "ValveBiped.Bip01_R_Hand" )
    local leftUpperarm = ply:LookupBone( "ValveBiped.Bip01_L_Upperarm" )
    local leftForearm = ply:LookupBone( "ValveBiped.Bip01_L_Forearm" )
    local leftHand = ply:LookupBone( "ValveBiped.Bip01_L_Hand" )

    if not rightUpperarm or not rightForearm or not rightHand or not leftUpperarm or not leftForearm or not leftHand then return end

    if state then
        ply:ManipulateBoneAngles( rightUpperarm, ANG_GRAB_RIGHT_UPPERARM )
        ply:ManipulateBoneAngles( rightForearm, ANG_GRAB_RIGHT_FOREARM )
        ply:ManipulateBoneAngles( rightHand, ANG_GRAB_RIGHT_HAND )
        ply:ManipulateBoneAngles( leftUpperarm, ANG_GRAB_LEFT_UPPERARM )
        ply:ManipulateBoneAngles( leftForearm, ANG_GRAB_LEFT_FOREARM )
        ply:ManipulateBoneAngles( leftHand, ANG_GRAB_LEFT_HAND )
    else
        ply:ManipulateBoneAngles( rightUpperarm, ANG_ZERO )
        ply:ManipulateBoneAngles( rightForearm, ANG_ZERO )
        ply:ManipulateBoneAngles( rightHand, ANG_ZERO )
        ply:ManipulateBoneAngles( leftUpperarm, ANG_ZERO )
        ply:ManipulateBoneAngles( leftForearm, ANG_ZERO )
        ply:ManipulateBoneAngles( leftHand, ANG_ZERO )
    end
end )
